version: '3.9'

services:
  db:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: VinApplication/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: vin-app
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=your_db;Username=your_user;Password=your_password"

  frontend:
    build:
      context: ./VinWeb   # assuming your Vite app is in a folder named 'frontend'
    container_name: vite-app
    ports:
      - "5173:5173"
    volumes:
      - ./VinWeb:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

volumes:
  pgdata:
